core/urls.py
from django.urls import path
from . import views

urlpatterns = [

	path('', views.AddDataView.as_view(), name='add_data'),

	path('ajax/load-subcategory/', views.LoadSubcategory.as_view(), name='ajax_load_subcategory'),
]

task/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.db import models

class Category(models.Model):
	name = models.CharField(max_length=500)

	def __str__(self):
		return self.name

class SubCategory(models.Model):
	name = models.CharField(max_length=500)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

class DataResult(models.Model):
	category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
	sub_category = models.ForeignKey(SubCategory, on_delete=models.SET_NULL, null=True)

core/forms.py
from django import forms

from .models import *

# Defining form to handle add data
class DataCreationForm(forms.ModelForm):
    class Meta:
        model = DataResult
        fields = '__all__'

core/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.contrib import messages

from .forms import DataCreationForm
from .models import *

# Class based view to handle add data form
class AddDataView(View):
    
    def get(self,request):
        form = DataCreationForm()
        category_list = Category.objects.all()
        return render(request, 'home.html', {'form': form, 'category_list' : category_list})

    def post(self, request):
        form = DataCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Data saved successfully!")
            return redirect('add_data')

        return render(request, 'home.html', {'form': form})

# AJAX to update the sub-category dropdown
class LoadSubcategory(View):
    def get(self, request):
        category_id = request.GET.get('category_id')
        try:
            subcategory = SubCategory.objects.filter(category_id=category_id).all()
        except SubCategory.DoesNotExist:
            subcategory = None
        return render(request, 'subcategory_dropdown.html', {'subcategory': subcategory})

core/templates/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Dependent Dropdown in Django</title>
</head>
<body>
    <div class="d-flex justify-content-center">
        <div class="row align-items-center justify-content-center">
            <div class="col">
                <h2>Data Form</h2>

        {% if messages %}
            {% for message in messages %}
                <p style="color: green;">{{ message }}</p>
            {% endfor %}
        {% endif %}

        <form method="post" id="DataForm" data-subcategory-url="{% url 'ajax_load_subcategory' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_category" class="form-label">Category:</label>
                <select name="category" class="form-select" required id="id_category">
                    <option value="" selected disabled>---------</option>
                    {% for each in category_list %}
                        <option value="{{ each.id }}">{{ each.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="id_category" class="form-label">Sub Category:</label>
                <select name="sub_category" class="form-select" required id="id_sub_category">
                    <option value="" selected disabled>---------</option>
                </select>
            </div>
            
            <input type="submit" class="btn btn-primary" value="Submit">
        
        </form>
            </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script>
    
    $("#id_category").change(function () {
        const url = $("#DataForm").attr("data-subcategory-url");  
        const categoryId = $(this).val();  

        if (categoryId){

            $.ajax({                       
            url: url,                    
            data: {
                'category_id': categoryId       
            },
            success: function (data) {   
                $("#id_sub_category").html(data); 
            }
        });
        }else{
        $("#id_sub_category").html("<option value=''>---------</option>");
        }
        
    });
</script>

</body>
</html>

core/templates/subcategory_dropdown.html
<option value="">---------</option>
{% for each in subcategory %}
<option value="{{ each.pk }}">{{ each.name }}</option>
{% endfor %}